
#define PERMISSIVE_HOLD

#undef BLE_NUS_MIN_INTERVAL
#undef BLE_NUS_MAX_INTERVAL
#undef BLE_HID_MAX_INTERVAL
#undef BLE_HID_SLAVE_LATENCY

#define TAPPING_TERM 160

#define BLE_NUS_MIN_INTERVAL 20
#define BLE_NUS_MAX_INTERVAL 40
#define BLE_HID_MAX_INTERVAL 40
#define BLE_HID_SLAVE_LATENCY 7
