

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
// #define TAPPING_TERM 160

#undef BLE_NUS_MIN_INTERVAL
#define BLE_NUS_MIN_INTERVAL 10
#undef BLE_NUS_MAX_INTERVAL
#define BLE_NUS_MAX_INTERVAL 30
#undef  BLE_HID_MAX_INTERVAL
#define BLE_HID_MAX_INTERVAL 30

#undef  BLE_SLAVE_LATENCY
#define BLE_SLAVE_LATENCY 3
