#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#define PREVENT_STUCK_MODIFIERS
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 160

#undef BLE_NUS_MIN_INTERVAL
#undef BLE_NUS_MAX_INTERVAL
#undef BLE_HID_MAX_INTERVAL
#undef BLE_HID_SLAVE_LATENCY

#define BLE_NUS_MIN_INTERVAL 25
#define BLE_NUS_MAX_INTERVAL 50
#define BLE_HID_MAX_INTERVAL 60
#define BLE_HID_SLAVE_LATENCY 4
#endif
